
configuration: Debug

install: 
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build: 
  # Updates the version number in the .vsixmanifest and updates the AppVeyor build number to match
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

build:
  project: VimAll.sln
  verbosity: minimal

after_build:
  - Src\CleanVsix\bin\Debug\CleanVsix.exe Src\VsVim\bin\Debug\VsVim.vsix

test_script:
  - Tools\xunit.console.clr4.x86.exe Test\VimCoreTest\bin\Debug\Vim.Core.UnitTest.dll /silent /noshadow
  - Tools\xunit.console.clr4.x86.exe Test\VimWpfTest\bin\Debug\Vim.UI.Wpf.UnitTest.dll /silent /noshadow
  - Tools\xunit.console.clr4.x86.exe Test\VsVimSharedTest\bin\Debug\Vim.VisualStudio.Shared.UnitTest.dll /silent /noshadow

after_test:
  # Pushes the compiled vsix to artifacts and publishes it to vsixgallery.com
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
